---
# simplify folder and command vars

- name: Check/define release name.
  set_fact: symfony_project_release="{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
  when: symfony_project_release == None

- name: Set symfony_current_release.
  set_fact: symfony_current_release="{{symfony_project_release}}_{{symfony_project_branch}}"

- name: Set symfony_current_release_dir.
  set_fact: symfony_current_release_dir="{{symfony_project_root}}/releases/{{symfony_current_release}}"

- name: Set symfony_shared_dir.
  set_fact: symfony_shared_dir="{{symfony_project_root}}/shared"

- name: Set symfony_console.
  set_fact: symfony_console="{{symfony_current_release_dir}}/{{symfony_project_console_command}} --env={{symfony_project_env}}"

- name: Set symfony_console without env.
  set_fact: symfony_console_without_env="{{symfony_current_release_dir}}/{{symfony_project_console_command}}"

- name: Get last release commit.
  local_action: command bash -c "git log --merges origin/master | grep -B5 -m1 -i \"release/\" | grep commit | awk '{print $2}'"
  register: last_release_commit_result

- name: Set last release commit.
  set_fact: last_release_commit="{{ last_release_commit_result.stdout }}"
