---
- name: Remove cache dir manually.
  file: state=absent path={{symfony_current_release_dir}}/app/cache/{{symfony_project_env}}
  when: symfony_project_enable_cache_warmup == True
  tags:
    - cache

- name: Warmup sf cache.
  shell: cd {{symfony_current_release_dir}} && export SYMFONY_ENV={{symfony_project_env}} && export SYMFONY_APP={{symfony_project_app}}; {{symfony_project_php_path}} {{symfony_console}} {{symfony_project_cache_command}} {{symfony_project_console_opts}}
  when: symfony_project_enable_cache_warmup == True
  async: 3600
  poll: 15
  tags:
    - cache
