- command: whoami
  register: local_username
  delegate_to: localhost
  ignore_errors: yes
  tags:
    - telegram


- command: hostname
  register: local_hostname
  delegate_to: localhost
  ignore_errors: yes
  tags:
    - telegram

- name: Send notification message via Telegram
  telegram:
    token: 480915656:AAFMd4U5IHDSqhkU05Y3wwH3lEb4DIV4hFQ
    chat_id: -1001412478176
    msg_format: markdown
    msg: '{{ local_username.stdout }}@{{ local_hostname.stdout }}: deploying {{symfony_project_branch}} to {{ inventory_hostname }}'
  delegate_to: localhost
  ignore_errors: yes
  tags:
    - telegram

- name: Notificate grafana about deployment start
  delegate_to: localhost
  ignore_errors: yes
  uri:
      url: "{{item.url}}"
      method: POST
      headers:
          Authorization: "{{item.token}}"
      body:
          text: '{{ local_username.stdout }}@{{ local_hostname.stdout }}: deploy started; branch {{symfony_project_branch}}'
          tags:
              - 'deploy_started'
              - '{{ inventory_hostname }}'
      body_format: json
      status_code: 200
  with_items:
      - {url: "{{ grafana_url }}", token: "{{ grafana_token }}"}
