---
- hosts: "{{ variable_host }}"
  roles:
      - mostbet.symfony3
  gather_facts: no

  vars_files:
      - grafana/credentials.yml

  vars:
      app_user: "{{ inventory_app_user | default('mostbet') }}"
      app_env: "{{ inventory_app_env|default('com') }}"

      symfony_project_warmup_prod: "{{ inventory_warmup_prod | default(warmup_prod) }}"
      symfony_project_skip_translations: "{{ inventory_skip_translations | default(skip_translations) }}"
      symfony_project_skip_old_frontend: "{{ inventory_skip_old_frontend | default(False) }}"
      ignore_old_release: "{{ inventory_ignore_old_release | default('n') }}"

      ansible_user: "{{ app_user }}"
      symfony_project_manage_composer: False

      symfony_project_root: "/var/www/{{ app_user }}"
      symfony_project_name: mostbet
      symfony_project_console_command: 'bin/console'
      symfony_project_composer_path: /usr/local/bin/composer
      symfony_project_repo: git@gitlab.com:datsteam/mostbet/mostbet.com.git
      symfony_project_env: stage

      symfony_project_console_opts: '--no-debug'
      symfony_project_copy_vendor: True
      symfony_project_fire_migrations: false

      symfony_project_branch: "{{ variable_branch }}"
      symfony_project_lock: "{{ variable_lock | default(false)}}"
      symfony_project_app: "{{ app_env }}"
      symfony_project_php_path: php
      symfony_project_keep_releases: 5

      crontab_folder: "{{ (app_env == 'com') | ternary('crontab', 'crontab_' ~ app_env) }}"
      symfony_project_crontab: /app/config/{{crontab_folder}}/crontab

      symfony_project_user:
          - "{{ app_user }}"
          - www-data

      symfony_project_composer_opts: '--optimize-autoloader --no-interaction'

      symfony_project_pre_run: hooks/dev/start_notification.yml
      symfony_project_post_run: hooks/dev/finish_notification.yml

      symfony_project_post_folder_creation_tasks: hooks/post_folder_creation.yml
      symfony_project_pre_cache_warmup_tasks: tasks/empty.yml
      symfony_project_pre_live_switch_tasks: hooks/dev/pre_live_switch_tasks.yml
      symfony_project_post_live_switch_tasks: hooks/dev/post_live_switch_my.yml

      symfony_project_shared_folders:
          - {name: logs, src: var/logs, path: var/logs}
          - {name: odds, src: var/odds, path: var/odds}
          - {name: secrets, src: var/secrets, path: var/secrets}
          - {name: upload, src: web/upload, path: web/upload}

      symfony_project_managed_folders:
          - {name: cache, path: var/cache}
          - {name: sessions, path: var/sessions}
      symfony_project_parameters_file: app_{{symfony_project_app}}/parameters.yml
